# Docker-compose file
# truffle with ganache testing environment setup
# f@keit424 Create @ 240816
# Version: 2.0
# Update @ 240819
# ===============================
# Version 2.0 update note:
# 1. Split services into 'ganache' & 'truffle'
# 2. 

version: '3.9'
services:
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    tty: true
    command:
      - --fork.network
      - mainnet
      - --chain.networkId 
      - "1"
      - --accounts
      - "10"
      - --wallet.seed
      - "1337"
      - --port
      - "8545"
      - --db
      - "/ganache_data"
      #- --hostname
      #- '0.0.0.0'


# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]